# ------------------------------------------------
# Camera Files

PRODUCT_COPY_FILES += \

vendor/amoi/l861/proprietary/lib64/hw/camera.mt6795.so:system/lib64/hw/camera.mt6795.so \
vendor/amoi/l861/proprietary/lib64/libcam.halsensor.so:system/lib64/libcam.halsensor.so \
vendor/amoi/l861/proprietary/lib64/libcam.metadata.so:system/lib64/libcam.metadata.so \
vendor/amoi/l861/proprietary/lib64/libaed.so:system/lib64/libaed.so \
vendor/amoi/l861/proprietary/lib/libaed.so:system/lib/libaed.so \
vendor/amoi/l861/proprietary/lib64/libcam_utils.so:system/lib64/libcam_utils.so \
vendor/amoi/l861/proprietary/lib64/libcamera_client_mtk.so:system/lib64/libcamera_client_mtk.so \
vendor/amoi/l861/proprietary/lib/libcamera_client_mtk.so:system/lib/libcamera_client_mtk.so \
vendor/amoi/l861/proprietary/lib64/libgralloc_extra.so:system/lib64/libgralloc_extra.so \
vendor/amoi/l861/proprietary/lib/libgralloc_extra.so:system/lib/libgralloc_extra.so \
vendor/amoi/l861/proprietary/lib64/libion.so:system/lib64/libion.so \
vendor/amoi/l861/proprietary/lib/libion.so:system/lib/libion.so \
vendor/amoi/l861/proprietary/lib64/libion_mtk.so:system/lib64/libion_mtk.so \
vendor/amoi/l861/proprietary/lib/libion_mtk.so:system/lib/libion_mtk.so \
vendor/amoi/l861/proprietary/lib64/libmtk_mmutils.so:system/lib64/libmtk_mmutils.so \
vendor/amoi/l861/proprietary/lib/libmtk_mmutils.so:system/lib/libmtk_mmutils.so \
vendor/amoi/l861/proprietary/lib64/libcam_platform.so:system/lib64/libcam_platform.so \
vendor/amoi/l861/proprietary/lib64/libcam.device1.so:system/lib64/libcam.device1.so \
vendor/amoi/l861/proprietary/lib64/libcam.camadapter.so:system/lib64/libcam.camadapter.so \
vendor/amoi/l861/proprietary/lib64/libJpgEncPipe.so:system/lib64/libJpgEncPipe.so \
vendor/amoi/l861/proprietary/lib64/libmtkjpeg.so:system/lib64/libmtkjpeg.so \
vendor/amoi/l861/proprietary/lib/libmtkjpeg.so:system/lib/libmtkjpeg.so \
vendor/amoi/l861/proprietary/lib64/libm4u.so:system/lib64/libm4u.so \
vendor/amoi/l861/proprietary/lib/libm4u.so:system/lib/libm4u.so \
vendor/amoi/l861/proprietary/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
vendor/amoi/l861/proprietary/lib64/libcam.camnode.so:system/lib64/libcam.camnode.so \
vendor/amoi/l861/proprietary/lib64/libcam.iopipe.so:system/lib64/libcam.iopipe.so \
vendor/amoi/l861/proprietary/lib64/libcam_hwutils.so:system/lib64/libcam_hwutils.so \
vendor/amoi/l861/proprietary/lib64/libcam_mmp.so:system/lib64/libcam_mmp.so \
vendor/amoi/l861/proprietary/lib/libcam_mmp.so:system/lib/libcam_mmp.so \
vendor/amoi/l861/proprietary/lib64/libstlport.so:system/lib64/libstlport.so \
vendor/amoi/l861/proprietary/lib/libstlport.so:system/lib/libstlport.so \
vendor/amoi/l861/proprietary/lib/libcam_hwutils.so:system/lib/libcam_hwutils.so \
vendor/amoi/l861/proprietary/lib64/libcamdrv.so:system/lib64/libcamdrv.so \
vendor/amoi/l861/proprietary/lib64/libbwc.so:system/lib64/libbwc.so \
vendor/amoi/l861/proprietary/lib64/librrc.so:system/lib64/librrc.so \
vendor/amoi/l861/proprietary/lib/librrc.so:system/lib/librrc.so \
vendor/amoi/l861/proprietary/lib/libbwc.so:system/lib/libbwc.so \
vendor/amoi/l861/proprietary/lib64/libcam.exif.so:system/lib64/libcam.exif.so \
vendor/amoi/l861/proprietary/lib/libcam.exif.so:system/lib/libcam.exif.so \
vendor/amoi/l861/proprietary/lib64/libcameracustom.so:system/lib64/libcameracustom.so \
vendor/amoi/l861/proprietary/lib64/libSonyIMX230PdafLibrary.so:system/lib64/libSonyIMX230PdafLibrary.so \
vendor/amoi/l861/proprietary/lib/libSonyIMX230PdafLibrary.so:system/lib/libSonyIMX230PdafLibrary.so \
vendor/amoi/l861/proprietary/lib/libcameracustom.so:system/lib/libcameracustom.so \
vendor/amoi/l861/proprietary/lib64/libmatv_cust.so:system/lib64/libmatv_cust.so \
vendor/amoi/l861/proprietary/lib/libmatv_cust.so:system/lib/libmatv_cust.so \
vendor/amoi/l861/proprietary/lib/libcamdrv.so:system/lib/libcamdrv.so \
vendor/amoi/l861/proprietary/lib64/libdpframework.so:system/lib64/libdpframework.so \
vendor/amoi/l861/proprietary/lib64/libpq_prot.so:system/lib64/libpq_prot.so \
vendor/amoi/l861/proprietary/lib64/libpq_cust.so:system/lib64/libpq_cust.so \
vendor/amoi/l861/proprietary/lib/libpq_cust.so:system/lib/libpq_cust.so \
vendor/amoi/l861/proprietary/lib/libpq_prot.so:system/lib/libpq_prot.so \
vendor/amoi/l861/proprietary/lib64/libvcodecdrv.so:system/lib64/libvcodecdrv.so \
vendor/amoi/l861/proprietary/lib64/libmtk_drvb.so:system/lib64/libmtk_drvb.so \
vendor/amoi/l861/proprietary/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
vendor/amoi/l861/proprietary/lib/libvcodecdrv.so:system/lib/libvcodecdrv.so \
vendor/amoi/l861/proprietary/lib64/libmtk_drvb.so:system/lib64/libmtk_drvb.so \
vendor/amoi/l861/proprietary/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
vendor/amoi/l861/proprietary/lib/libvcodecdrv.so:system/lib/libvcodecdrv.so \
vendor/amoi/l861/proprietary/lib/libmp4enc_sa.ca7.so:system/lib/libmp4enc_sa.ca7.so \
vendor/amoi/l861/proprietary/lib/libvcodec_utility.so:system/lib/libvcodec_utility.so \
vendor/amoi/l861/proprietary/lib/libvcodec_oal.so:system/lib/libvcodec_oal.so \
vendor/amoi/l861/proprietary/lib/libvc1dec_sa.ca7.so:system/lib/libvc1dec_sa.ca7.so \
vendor/amoi/l861/proprietary/lib/libvp8dec_sa.ca7.so:system/lib/libvp8dec_sa.ca7.so \
vendor/amoi/l861/proprietary/lib/libvp8enc_sa.ca7.so:system/lib/libvp8enc_sa.ca7.so \
vendor/amoi/l861/proprietary/lib/libvp9dec_sa.ca7.so:system/lib/libvp9dec_sa.ca7.so \
vendor/amoi/l861/proprietary/lib64/libmmprofile.so:system/lib64/libmmprofile.so \
vendor/amoi/l861/proprietary/lib/libmmprofile.so:system/lib/libmmprofile.so \
vendor/amoi/l861/proprietary/lib64/libperfservicenative.so:system/lib64/libperfservicenative.so \
vendor/amoi/l861/proprietary/lib/libperfservicenative.so:system/lib/libperfservicenative.so \
vendor/amoi/l861/proprietary/lib/libdpframework.so:system/lib/libdpframework.so \
vendor/amoi/l861/proprietary/lib64/libimageio.so:system/lib64/libimageio.so \
vendor/amoi/l861/proprietary/lib64/libimageio_plat_drv.so:system/lib64/libimageio_plat_drv.so \
vendor/amoi/l861/proprietary/lib/libimageio_plat_drv.so:system/lib/libimageio_plat_drv.so \
vendor/amoi/l861/proprietary/lib/libimageio.so:system/lib/libimageio.so \
vendor/amoi/l861/proprietary/lib/libcam.iopipe.so:system/lib/libcam.iopipe.so \
vendor/amoi/l861/proprietary/lib64/libcam.paramsmgr.so:system/lib64/libcam.paramsmgr.so \
vendor/amoi/l861/proprietary/lib64/libfeatureio.so:system/lib64/libfeatureio.so \
vendor/amoi/l861/proprietary/lib64/lib3a.so:system/lib64/lib3a.so \
vendor/amoi/l861/proprietary/lib/lib3a.so:system/lib/lib3a.so \
vendor/amoi/l861/proprietary/lib64/lib3a_sample.so:system/lib64/lib3a_sample.so \
vendor/amoi/l861/proprietary/lib/lib3a_sample.so:system/lib/lib3a_sample.so \
vendor/amoi/l861/proprietary/lib64/libcam.utils.so:system/lib64/libcam.utils.so \
vendor/amoi/l861/proprietary/lib/libcam.utils.so:system/lib/libcam.utils.so \
vendor/amoi/l861/proprietary/lib64/libcam.utils.sensorlistener.so:system/lib64/libcam.utils.sensorlistener.so \
vendor/amoi/l861/proprietary/lib/libcam.utils.sensorlistener.so:system/lib/libcam.utils.sensorlistener.so \
vendor/amoi/l861/proprietary/lib64/libcamalgo.so:system/lib64/libcamalgo.so \
vendor/amoi/l861/proprietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
vendor/amoi/l861/proprietary/lib64/libn3d3a.so:system/lib64/libn3d3a.so \
vendor/amoi/l861/proprietary/lib/libn3d3a.so:system/lib/libn3d3a.so \
vendor/amoi/l861/proprietary/lib64/libnvram.so:system/lib64/libnvram.so \
vendor/amoi/l861/proprietary/lib64/libcustom_nvram.so:system/lib64/libcustom_nvram.so \
vendor/amoi/l861/proprietary/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
vendor/amoi/l861/proprietary/lib64/libnvram_platform.so:system/lib64/libnvram_platform.so \
vendor/amoi/l861/proprietary/lib/libnvram_platform.so:system/lib/libnvram_platform.so \
vendor/amoi/l861/proprietary/lib64/libnvram_sec.so:system/lib64/libnvram_sec.so \
vendor/amoi/l861/proprietary/lib/libnvram_sec.so:system/lib/libnvram_sec.so \
vendor/amoi/l861/proprietary/lib/libnvram.so:system/lib/libnvram.so \
vendor/amoi/l861/proprietary/lib64/libnvramagentclient.so:system/lib64/libnvramagentclient.so \
vendor/amoi/l861/proprietary/lib/libnvramagentclient.so:system/lib/libnvramagentclient.so \
vendor/amoi/l861/proprietary/lib/libfeatureio.so:system/lib/libfeatureio.so \
vendor/amoi/l861/proprietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
vendor/amoi/l861/proprietary/lib/libcam.camnode.so:system/lib/libcam.camnode.so \
vendor/amoi/l861/proprietary/lib64/libcam.camshot.so:system/lib64/libcam.camshot.so \
vendor/amoi/l861/proprietary/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
vendor/amoi/l861/proprietary/lib64/libcam.utils.cpuctrl.so:system/lib64/libcam.utils.cpuctrl.so \
vendor/amoi/l861/proprietary/lib/libcam.utils.cpuctrl.so:system/lib/libcam.utils.cpuctrl.so \
vendor/amoi/l861/proprietary/lib64/libcam1_utils.so:system/lib64/libcam1_utils.so \
vendor/amoi/l861/proprietary/lib/libcam1_utils.so:system/lib/libcam1_utils.so \
vendor/amoi/l861/proprietary/lib64/libdngop.so:system/lib64/libdngop.so \
vendor/amoi/l861/proprietary/lib/libdngop.so:system/lib/libdngop.so \
vendor/amoi/l861/proprietary/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
vendor/amoi/l861/proprietary/lib64/libcam.client.so:system/lib64/libcam.client.so \
vendor/amoi/l861/proprietary/lib64/libmpo.so:system/lib64/libmpo.so \
vendor/amoi/l861/proprietary/lib/libmpo.so:system/lib/libmpo.so \
vendor/amoi/l861/proprietary/lib64/libmpoencoder.so:system/lib64/libmpoencoder.so \
vendor/amoi/l861/proprietary/lib/libmpoencoder.so:system/lib/libmpoencoder.so \
vendor/amoi/l861/proprietary/lib/libcam.client.so:system/lib/libcam.client.so \
vendor/amoi/l861/proprietary/lib/libcam.device1.so:system/lib/libcam.device1.so \
vendor/amoi/l861/proprietary/lib/libcam_platform.so:system/lib/libcam_platform.so \
vendor/amoi/l861/proprietary/lib/libcam_utils.so:system/lib/libcam_utils.so \
vendor/amoi/l861/proprietary/lib/libcam.metadata.so:system/lib/libcam.metadata.so \
vendor/amoi/l861/proprietary/lib/libcam.halsensor.so:system/lib/libcam.halsensor.so \
vendor/amoi/l861/proprietary/lib64/libmmsdkservice.so:system/lib64/libmmsdkservice.so \
vendor/amoi/l861/proprietary/lib64/libcam.sdkclient.so:system/lib64/libcam.sdkclient.so \
vendor/amoi/l861/proprietary/lib/libcam.sdkclient.so:system/lib/libcam.sdkclient.so \
vendor/amoi/l861/proprietary/lib64/libmmsdkservice.feature.so:system/lib64/libmmsdkservice.feature.so \
vendor/amoi/l861/proprietary/lib/libmmsdkservice.feature.so:system/lib/libmmsdkservice.feature.so \
vendor/amoi/l861/proprietary/lib/libmmsdkservice.so:system/lib/libmmsdkservice.so \
vendor/amoi/l861/proprietary/lib/hw/camera.mt6795.so:system/lib/hw/camera.mt6795.so \

# ------------------------------------------------
